[workspace]
members = [
  "adaptors/cli",
  "adaptors/fs",
  "adaptors/rest",
  "applications/rest-server",
  "applications/rjira",
  "cores/backlog",
  "ports/driven/backlog-repo",
  "ports/driver/backlog-service",
]
